map:
  patternProperties:
    ".*":
      type: map
      mapping:
        topics:
          map(include('topic'), required=False, none=False)
        services:
          map(include('service'), required=False, none=False)
        actions:
          map(include('action'), required=False, none=False)
---
topic:
  regex(".*"):
    type: map
    mapping:
      headers_file: str(none=False)
      parameters: list(map(str(), num()))
      source: str(none=False)
      type: str(none=False)

service:
  regex(".*"):
    type: map
    mapping:
      headers_file: str(none=False)
      parameters: list(map(str(), num()))
      source: str(none=False)
      type: str(none=False)

action:
  regex(".*"):
    type: map
    mapping:
      headers_file: str(none=False)
      parameters: list(map(str(), num()))
      source: str(none=False)
      type: str(none=False)
