map:
  patternProperties:
    ".*":
      topics: map(include('base_format'), required=False, none=False)
      services: map(include('base_format'), required=False, none=False)
      actions: map(include('base_format'), required=False, none=False)
---
base_format:
  regex(".*"): map(include('type_indicator'), required=True, none=False)
---
type_indicator:
  headers_file: str(none=False)
  parameters: list(map(str(), num()))
  source: str(none=False)
  type: str(none=False)