map(include('package_format'))
---
package_format:
  topics: map(include('type_indicator'), required=False, none=False)
  services: map(include('type_indicator'), required=False, none=False)
  actions: map(include('type_indicator'), required=False, none=False)
---
type_indicator:
  headers_file: str(none=False)
  node_name: str(none=False, required=False)
  parameters: list(map(str(), num()))
  source: str(none=False)
  type: str(none=False)